version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    container_name: app.dev
    volumes:
        - .:/go/src/api
    working_dir: /go/src/api
    # command: go run main.go
    tty: true
    ports:
      - "3000:3000"